version: '3.8'
services:
  db:
    image: postgres:latest
    env_file:
      - ./.env
    ports:
      - 5431:5432 # not to conflict with other postgres
    volumes:
      - ./.data/postgres:/data/postgres